module.exports = {
	skills: [
		{
			charter: 'Programming Languages',
			values: [
				{ title: 'С', level: 50 },
				{ title: 'С++', level: 50 },
				{ title: 'С#', level: 20 },
				{ title: 'Javascript', level: 70 },
				{ title: 'HTML', level: 80 },
				{ title: 'CSS', level: 80 },
				{ title: 'PHP', level: 10 },
				{ title: 'DART', level: 15 },
			],
		},
		{
			charter: 'Languages',
			values: [
				{ title: 'Russian', level: 70 },
				{ title: 'Ukrainian', level: 70 },
				{ title: 'English', level: 20 },
			],
		},
		{
			charter: 'Technologies',
			values: [
				{ title: 'React JS', level: 30 },
				{ title: 'Qt', level: 50 },
				{ title: 'Webpack', level: 65 },
				{ title: 'Eslint', level: 90 },
				{ title: 'Stylelint', level: 90 },
			],
		},
		{
			charter: 'Design',
			values: [
				{ title: 'Photoshop', level: 60 },
				{ title: 'Figma', level: 75 },
			],
		},
	],

	works: [
		{
			id: 1,
			title: 'Webland',
			category: 'javascript',
			date: '2021-05-27T19:28:29Z',
			link: 'https://github.com/luamoris/webland',
			img: null,
			tags: ['javascript', 'portfolio', 'scss', 'html', 'webpack'],
		},
		{
			id: 2,
			title: 'Test 300x300',
			category: 'test',
			date: '2020-05-27T19:28:29Z',
			link: 'https://github.com/luamoris',
			img: './img/test/300x300.svg',
			tags: ['img', 'test'],
		},
		{
			id: 3,
			title: 'Test 300x400',
			category: 'test',
			date: '2019-05-27T19:28:29Z',
			link: 'https://github.com/luamoris',
			img: './img/test/300x400.svg',
			tags: ['img', 'test'],
		},
		{
			id: 4,
			title: 'Test 400x300',
			category: 'test',
			date: '2017-05-27T19:28:29Z',
			link: 'https://github.com/luamoris',
			img: './img/test/400x300.svg',
			tags: ['img', 'test'],
		},
		{
			id: 5,
			title: 'Default 300x300',
			category: 'test',
			date: '2016-05-27T19:28:29Z',
			link: 'https://github.com/luamoris',
			img: './img/gallery/default.svg',
			tags: ['img', 'test', 'default'],
		},
		{
			id: 6,
			title: 'Db coursework',
			category: 'javascript',
			date: '2021-05-26T11:52:53Z',
			link: 'https://github.com/luamoris/db_coursework',
			img: null,
			tags: ['coursework', 'javascript', 'database'],
		},
		{
			id: 7,
			title: 'Simulator street fight',
			category: 'javascript',
			date: '2021-05-10T07:54:31Z',
			link: 'https://github.com/luamoris/simulator-street-fight',
			img: null,
			tags: ['simulator', 'javascript', 'game'],
		},
		{
			id: 8,
			title: 'Teachinder',
			category: 'javascript',
			date: '2021-05-06T03:29:44Z',
			link: 'https://github.com/luamoris/teachinder',
			img: null,
			tags: ['teachinder', 'javascript', 'web'],
		},
		{
			id: 9,
			title: 'Homepage',
			category: 'javascript',
			date: '2021-05-04T16:08:48Z',
			link: 'https://github.com/luamoris/homepage',
			img: null,
			tags: ['homepage', 'javascript', 'academy'],
		},
		{
			id: 10,
			title: 'Smic',
			category: 'javascript',
			date: '2021-05-02T00:46:26Z',
			link: 'https://github.com/luamoris/smic',
			img: null,
			tags: ['smic', 'javascript', 'npm'],
		},
		{
			id: 11,
			title: 'Test cases',
			category: 'javascript',
			date: '2021-04-29T12:54:12Z',
			link: 'https://github.com/luamoris/test-cases',
			img: null,
			tags: ['test', 'javascript', 'cases'],
		},
		{
			id: 12,
			title: 'Tutorial',
			category: 'javascript',
			date: '2021-04-10T21:59:56Z',
			link: 'https://github.com/luamoris/tutorial',
			img: null,
			tags: ['javascript', 'tutorial', 'gitbook', 'md'],
		},
		{
			id: 13,
			title: 'Gitbook plugin block-code',
			category: 'javascript',
			date: '2021-04-12T19:56:48Z',
			link: 'https://github.com/luamoris/gitbook-plugin-block-code',
			img: null,
			tags: ['javascript', 'gitbook', 'plugin', 'block', 'code', 'npm'],
		},
		{
			id: 14,
			title: 'React social network',
			category: 'react',
			date: '2021-04-09T19:18:08Z',
			link: 'https://github.com/luamoris/react-social-network',
			img: null,
			tags: ['react', 'social', 'network'],
		},
		{
			id: 15,
			title: 'React FAQ',
			category: 'react',
			date: '2021-03-28T13:35:43Z',
			link: 'https://github.com/luamoris/react-faq-card-info',
			img: null,
			tags: ['react', 'faq', 'card'],
		},
		{
			id: 16,
			title: 'Webpack boilerplate',
			category: 'javascript',
			date: '2021-03-28T13:34:13Z',
			link: 'https://github.com/luamoris/webpack-boilerplate',
			img: null,
			tags: ['webpack', 'boilerplate', 'javascript'],
		},
		{
			id: 17,
			title: 'Covid game',
			category: 'react',
			date: '2021-03-28T13:37:37Z',
			link: 'https://github.com/luamoris/covid-game',
			img: null,
			tags: ['react', 'covid', 'game'],
		},
		{
			id: 18,
			title: 'Estiemic',
			category: 'javascript',
			date: '2021-01-25T20:13:48Z',
			link: 'https://github.com/luamoris/estiemic',
			img: null,
			tags: ['bot', 'javascript', 'telegram'],
		},
		{
			id: 19,
			title: 'Forum',
			category: 'php',
			date: '2020-12-15T15:54:44Z',
			link: 'https://github.com/luamoris/forum',
			img: null,
			tags: ['php', 'html', 'forum'],
		},
		{
			id: 20,
			title: 'Icons',
			category: 'javascript',
			date: '2020-11-29T09:38:02Z',
			link: 'https://github.com/luamoris/icons',
			img: null,
			tags: ['javascript', 'icon', 'icons'],
		},
	],
};
